package com.zytproduct.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TL_DIAGNOSE_ITEM.
 */
public class TlDiagnoseItem {

    private Long diagnoseId;
    /** Not-null value. */
    private String diagnoseDesc;
    private long parentId;
    private long leafFlag;
    private Long diseaseId;

    public TlDiagnoseItem() {
    }

    public TlDiagnoseItem(Long diagnoseId) {
        this.diagnoseId = diagnoseId;
    }

    public TlDiagnoseItem(Long diagnoseId, String diagnoseDesc, long parentId, long leafFlag, Long diseaseId) {
        this.diagnoseId = diagnoseId;
        this.diagnoseDesc = diagnoseDesc;
        this.parentId = parentId;
        this.leafFlag = leafFlag;
        this.diseaseId = diseaseId;
    }

    public Long getDiagnoseId() {
        return diagnoseId;
    }

    public void setDiagnoseId(Long diagnoseId) {
        this.diagnoseId = diagnoseId;
    }

    /** Not-null value. */
    public String getDiagnoseDesc() {
        return diagnoseDesc;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDiagnoseDesc(String diagnoseDesc) {
        this.diagnoseDesc = diagnoseDesc;
    }

    public long getParentId() {
        return parentId;
    }

    public void setParentId(long parentId) {
        this.parentId = parentId;
    }

    public long getLeafFlag() {
        return leafFlag;
    }

    public void setLeafFlag(long leafFlag) {
        this.leafFlag = leafFlag;
    }

    public Long getDiseaseId() {
        return diseaseId;
    }

    public void setDiseaseId(Long diseaseId) {
        this.diseaseId = diseaseId;
    }

}
