package com.zytproduct.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TL_DISEASE.
 */
public class TlDisease {

    private Long diseaseId;
    /** Not-null value. */
    private String diseaseName;
    private String diseaseUrl;

    public TlDisease() {
    }

    public TlDisease(Long diseaseId) {
        this.diseaseId = diseaseId;
    }

    public TlDisease(Long diseaseId, String diseaseName, String diseaseUrl) {
        this.diseaseId = diseaseId;
        this.diseaseName = diseaseName;
        this.diseaseUrl = diseaseUrl;
    }

    public Long getDiseaseId() {
        return diseaseId;
    }

    public void setDiseaseId(Long diseaseId) {
        this.diseaseId = diseaseId;
    }

    /** Not-null value. */
    public String getDiseaseName() {
        return diseaseName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDiseaseName(String diseaseName) {
        this.diseaseName = diseaseName;
    }

    public String getDiseaseUrl() {
        return diseaseUrl;
    }

    public void setDiseaseUrl(String diseaseUrl) {
        this.diseaseUrl = diseaseUrl;
    }

}
