package com.zytproduct.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TL_PEST.
 */
public class TlPest {

    private Long pestId;
    /** Not-null value. */
    private String pestName;
    private String pestUrl;

    public TlPest() {
    }

    public TlPest(Long pestId) {
        this.pestId = pestId;
    }

    public TlPest(Long pestId, String pestName, String pestUrl) {
        this.pestId = pestId;
        this.pestName = pestName;
        this.pestUrl = pestUrl;
    }

    public Long getPestId() {
        return pestId;
    }

    public void setPestId(Long pestId) {
        this.pestId = pestId;
    }

    /** Not-null value. */
    public String getPestName() {
        return pestName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPestName(String pestName) {
        this.pestName = pestName;
    }

    public String getPestUrl() {
        return pestUrl;
    }

    public void setPestUrl(String pestUrl) {
        this.pestUrl = pestUrl;
    }

}
